name: GraalVM CE CI
on: [push, pull_request]

env:
  DOCKER_USERNAME: laurihuotari

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-

      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: 21.3.0.java17

      - name: Install Native Image
        run: gu install native-image

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push Docker Image
        uses: gradle/gradle-build-action@v1
        with:
          gradle-version: 7.3.3
        env:
          DOCKER_REGISTRY_URL: registry.hub.docker.com
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          export DOCKER_IMAGE=`echo "${DOCKER_REGISTRY_URL}/${DOCKER_USERNAME}/proxmox-api" | sed -e 's#//#/#' -e 's#^/##'`
          gradle check dockerPushNative --no-daemon
